Controllers/DashboardController.cs
using Excursion.Interfaces;
using Excursion.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Excursion.Controllers
{
    public class DashboardController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IDashboardRepository _dashboardRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DashboardController(UserManager<AppUser> userManager, IDashboardRepository dashboardRepository, IHttpContextAccessor httpContextAccessor)
        {
            _userManager = userManager;
            _dashboardRepository = dashboardRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        // Displays the user's bookings.
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            if (curUserId == null) return View("Error");
            var bookings = await _dashboardRepository.GetUserBookingsAsync(curUserId);

            return View(bookings);
        }


        // Shows a view to confirm the cancellation of a booking.
        [HttpGet]
        public async Task<IActionResult> Cancel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (User.Identity?.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }

            var booking = await _dashboardRepository.GetBookingByIdAsync(id.Value);

            var currentUserId = _httpContextAccessor.HttpContext?.User.GetUserId();

            // Check if the booking belongs to the current user.
            if (booking == null || booking.AppUser.Id != currentUserId || currentUserId == null)
            {
                return Unauthorized();
            }

            return View(booking);
        }

        // Processes the cancellation of the user's booking.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelConfirmed(int? id)
        {
            if (id == null) return NotFound();

            var booking = await _dashboardRepository.GetBookingByIdAsync(id.Value);

            var currentUserId = _httpContextAccessor.HttpContext?.User.GetUserId();

            if (booking == null || booking.AppUser.Id != currentUserId || currentUserId == null)
            {
                return Unauthorized();
            }
            var result = await _dashboardRepository.RemoveBookingAsync(booking);

            return View(booking);
        }



    }

}

Controllers/TourController.cs
using Excursion.Interfaces;
using Excursion.Models;
using Excursion.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Excursion.Controllers
{
    public class TourController : Controller
    {
        // Dependency Injection for the tour repository
        private readonly ITourRepository _tourRepository;

        // Constructor accepting the tour repository
        public TourController(ITourRepository tourRepository)
        {
            _tourRepository = tourRepository;
        }

        // Action method for the main tour listing, with an optional search term
        public async Task<IActionResult> Index(string searchTerm)
        {
            IEnumerable<Tour> tours;

            // Check if the search term is provided or not
            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                 tours = await _tourRepository.GetAll();
            }
            else
            {
                tours = await _tourRepository.SearchToursAsync(searchTerm);
            }

            // Return the corresponding tours to the view
            return View(tours);
        }

        // Action method to display details of a specific tour
        public async Task<IActionResult> Detail(int id)
        {
            Tour tour = await _tourRepository.GetByIdAsync(id);
            return View(tour);
        }

        // Action method to display the tour creation form; only accessible by admins
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // Action method to handle the submission of the tour creation form
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Create(CreateTourViewModel tourVM)
        {
            // Validate the model data
            if (ModelState.IsValid)
            {
                // Map the ViewModel to the Data Model
                var tour = new Tour
                {
                    Name = tourVM.Name,
                    Description = tourVM.Description,
                    Price = tourVM.Price,
                    Image = tourVM.Image,
                    Minor = tourVM.Minor,
                    Address = new Address()
                    {
                        Street = tourVM.Address.Street,
                        City = tourVM.Address.City,
                        Country = tourVM.Address.Country
                    },
                };

                // Add the tour to the repository
                _tourRepository.Add(tour);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Unsuccessful");
            }

            // If model state is invalid, return to the creation form with provided data
            return View(tourVM);
        }

        // Action method to display the tour edit form; only accessible by admins
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var tour = await _tourRepository.GetByIdAsync(id);
            if (tour == null) return View("Error");

            var tourVM = new EditTourViewModel
            {
                Name = tour.Name,
                Description = tour.Description,
                Price = tour.Price,
                Image = tour.Image,
                AddressId = tour.AddressId,
                Address = tour.Address,
                Minor = tour.Minor,
            };

            return View(tourVM);
        }

        // Action method to handle the submission of the tour edit form
        [HttpPost]
        public IActionResult Edit(int id, EditTourViewModel tourVM)
        {
            // Validate the model data
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit the excursion");
                return View("Edit", tourVM);
            }

            // Map the ViewModel to the Data Model
            var tour = new Tour
            {
                Id = id,
                Name = tourVM.Name,
                Description = tourVM.Description,
                Price = tourVM.Price,
                Image = tourVM.Image,
                Minor = tourVM.Minor,
                Address = new Address()
                {
                    Street = tourVM.Address.Street,
                    City = tourVM.Address.City,
                    Country = tourVM.Address.Country
                },
            };

            // Update the tour in the repository
            _tourRepository.Update(tour);
            return RedirectToAction("Index");
        }
    }
}

Controllers/UserController.cs
using Excursion.Models;
using Excursion.Interfaces;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Excursion.Controllers
{
    public class UserController : Controller
    {
        
        private readonly IUserRepository _userRepository;
        
        private readonly UserManager<AppUser> _userManager;

        public UserController(IUserRepository userRepository, UserManager<AppUser> userManager)
        {
            _userRepository = userRepository;
            _userManager = userManager;
        }

        // Endpoint to list all users, accessible only to the admin role
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> ListUsers()
        {
            var users = await _userRepository.GetAllUsersAsync(); // Fetch all users
            return View(users);
        }

        // Endpoint to display bookings of a specific user, accessible only to the admin role
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UserBookings(string id)
        {
            var bookings = await _userRepository.GetBookingsForUser(id);
            var user = await _userManager.FindByIdAsync(id); 
            ViewBag.Username = user?.UserName; // Pass the username to the view

            if (bookings == null) return View("Error"); // Handle if bookings data isn't available
            return View(bookings);
        }
    }
}

Views/Dashboard/Cancel.cshtml
@model Excursion.Models.Booking
<link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
<div class="form">
    <h1>Cancel Booking</h1>

    <p>Are you sure you want to cancel the following booking?</p>

    <p>Excursion: @Model.Tour?.Name</p>
    <p>Date: @Model.TourDate.ToString("d")</p>
    <p>Number of Guests: @Model.NumberOfGuests</p>
    <p>Total Cost: £@Model.TotalCost</p>

    <form asp-controller="Dashboard" asp-action="CancelConfirmed" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirm cancellation" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Go back</a>
    </form>
</div>

Views/Dashboard/CancelConfirmed.cshtml

<div class="form bookings">
<h1>Booking cancelled</h1>
<br>
<p>Your booking has been successfully cancelled.</p>
<br>
<a asp-action="Index" class="btn btn-secondary">Back to list</a>
</div>


Views/Dashboard/Index.cshtml
@model IEnumerable<Excursion.Models.Booking>



<link rel="stylesheet" href="~/css/dashboard.css" asp-append-version="true" />
@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
{
    <div class="tile-buttons">
        <div class="tile">
            <a asp-controller="User" asp-action="listusers"><i class="fa-regular fa-user fa-3x"></i> User Management</a>
        </div>
        <div class="tile">
            <a asp-controller="Tour" asp-action="Index"><i class="fa-solid fa-list-check fa-3x"></i>Tour Management</a>
        </div>
               <div class="tile">
            <a asp-controller="Tour" asp-action="Create"><i class="fa-solid fa-plus fa-3x"></i>Create New Excursion</a>
        </div>
    </div>

    
}


<div class="form bookings">
    <h1>My Bookings</h1>
@if (!Model.Any())
{
    <p>You have no bookings yet.</p>
}

else
{
    
        <table class="table">
            <thead>
                <tr>
                    <th>Tour Name</th>
                    <th>Date</th>
                    <th>Number of Guests</th>
                    <th>Total Cost</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var booking in Model)
                {
                    <tr>
                        <td>@booking.Tour?.Name</td>
                        <td>@booking.TourDate.ToString("d")</td>
                        <td>@booking.NumberOfGuests</td>
                        <td>£@booking.TotalCost</td>
                        <td>
                            <button class="btn btn-danger">
                                <a asp-controller="Dashboard" asp-action="Cancel" asp-route-id="@booking.Id" class="text-white">
                                    <i class="fa-solid fa-square-xmark"></i> Cancel</a>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

}
</div>