Models/Booking.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Excursion.Models
{
    public class Booking
    {
        public int Id { get; set; }
        
        [ForeignKey("Tour")]
        public int TourId { get; set; }
        public Tour? Tour { get; set; }
        public DateTime TourDate { get; set; }
        public int NumberOfGuests { get; set; }
        public double TotalCost { get; set; }
        public string? BookingNotes { get; set; }
        public AppUser? AppUser { get; set; }
        


    }
}

ViewModels/BookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Excursion.Models;

namespace Excursion.ViewModels
{
    public class BookViewModel
    {
        public int Id { get; set; }
        public int TourId { get; set; }
        public Tour? Tour { get; set; }
        [DataType(DataType.Date)]
        public DateTime TourDate { get; set; }
        public int NumberOfGuests { get; set; }
        public double? TotalCost { get; set; }
        public string? BookingNotes { get; set; }



    }
}

Controllers/BookingController.cs
using Excursion.Interfaces;
using Excursion.Models;
using Excursion.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace Excursion.Controllers
{
    // Controller responsible for booking operations.
    public class BookingController : Controller
    {
       // Dependency injection.
        private readonly IBookingRepository _bookingRepository;
        private readonly ITourRepository _tourRepository;

        
        public BookingController(IBookingRepository bookingRepository, ITourRepository tourRepository)
        {
            _bookingRepository = bookingRepository;
            _tourRepository = tourRepository;
        }

        // GET action for booking a tour with a given ID.
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Book(int id)
        {
            Tour tour = await _tourRepository.GetByIdAsync(id);
            if (tour == null) return View("Error");
            var bookVM = new BookViewModel
            {
                TourId = tour.Id,
                Tour = tour
            };
            return View(bookVM);
        }

        // POST action to handle the booking submission.
        [Authorize]
        [HttpPost("Booking/Book/{id}")]
        public async Task<IActionResult> Book(BookViewModel bookVM, int id)
        {
            
            var tour = await _tourRepository.GetByIdAsync(id);
            if (tour == null) return View("Error");

            // Calculate total booking cost.
            double totalCost = CalculateTotalCost(tour.Price, bookVM.NumberOfGuests);

            // Create new booking record.
            var booking = new Booking
            {
                Tour = tour,
                TourDate = bookVM.TourDate,
                NumberOfGuests = bookVM.NumberOfGuests,
                BookingNotes = bookVM.BookingNotes,
                TotalCost = totalCost,
            };

            // Attach booking to current user and save.
            var user = await _bookingRepository.GetCurrentUserAsync();
            if (user.Bookings == null)
            {
                user.Bookings = new List<Booking>();
            }
            user.Bookings.Add(booking);
            _bookingRepository.Update(user);

            // Redirect to the booking confirmation view.
            return RedirectToAction("Confirmation", new { id = booking.Id });
        }

        // Helper method to calculate the total booking cost.
        private double CalculateTotalCost(double pricePerGuest, int numberOfGuests)
        {
            return numberOfGuests * pricePerGuest;
        }

        // Confirmation view for a specific booking by its ID.
        public async Task<IActionResult> Confirmation(int id)
        {
            var booking = await _bookingRepository.GetBookingByIdAsync(id);

            if (booking == null) return View("Error");

            return View(booking);
        }

        // POST action to cancel a booking by its ID.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancel(int id)
        {
            var booking = await _bookingRepository.GetBookingByIdAsync(id);

            if (booking == null) return View("Error");

            // Remove the booking.
            var result = await _bookingRepository.RemoveBookingAsync(booking);
            if (!result)
            {
                return View("Error");
            }

            // Redirect to the home page after successful cancellation.
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/DashboardController.cs
using Excursion.Interfaces;
using Excursion.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Excursion.Controllers
{
    public class DashboardController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IDashboardRepository _dashboardRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DashboardController(UserManager<AppUser> userManager, IDashboardRepository dashboardRepository, IHttpContextAccessor httpContextAccessor)
        {
            _userManager = userManager;
            _dashboardRepository = dashboardRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        // Displays the user's bookings.
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var curUserId = _httpContextAccessor.HttpContext?.User.GetUserId();
            if (curUserId == null) return View("Error");
            var bookings = await _dashboardRepository.GetUserBookingsAsync(curUserId);

            return View(bookings);
        }


        // Shows a view to confirm the cancellation of a booking.
        [HttpGet]
        public async Task<IActionResult> Cancel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            if (User.Identity?.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Account");
            }

            var booking = await _dashboardRepository.GetBookingByIdAsync(id.Value);

            var currentUserId = _httpContextAccessor.HttpContext?.User.GetUserId();

            // Check if the booking belongs to the current user.
            if (booking == null || booking.AppUser.Id != currentUserId || currentUserId == null)
            {
                return Unauthorized();
            }

            return View(booking);
        }

        // Processes the cancellation of the user's booking.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelConfirmed(int? id)
        {
            if (id == null) return NotFound();

            var booking = await _dashboardRepository.GetBookingByIdAsync(id.Value);

            var currentUserId = _httpContextAccessor.HttpContext?.User.GetUserId();

            if (booking == null || booking.AppUser.Id != currentUserId || currentUserId == null)
            {
                return Unauthorized();
            }
            var result = await _dashboardRepository.RemoveBookingAsync(booking);

            return View(booking);
        }



    }

}

Controllers/TourController.cs
using Excursion.Interfaces;
using Excursion.Models;
using Excursion.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Excursion.Controllers
{
    public class TourController : Controller
    {
        // Dependency Injection for the tour repository
        private readonly ITourRepository _tourRepository;

        // Constructor accepting the tour repository
        public TourController(ITourRepository tourRepository)
        {
            _tourRepository = tourRepository;
        }

        // Action method for the main tour listing, with an optional search term
        public async Task<IActionResult> Index(string searchTerm)
        {
            IEnumerable<Tour> tours;

            // Check if the search term is provided or not
            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                 tours = await _tourRepository.GetAll();
            }
            else
            {
                tours = await _tourRepository.SearchToursAsync(searchTerm);
            }

            // Return the corresponding tours to the view
            return View(tours);
        }

        // Action method to display details of a specific tour
        public async Task<IActionResult> Detail(int id)
        {
            Tour tour = await _tourRepository.GetByIdAsync(id);
            return View(tour);
        }

        // Action method to display the tour creation form; only accessible by admins
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // Action method to handle the submission of the tour creation form
        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Create(CreateTourViewModel tourVM)
        {
            // Validate the model data
            if (ModelState.IsValid)
            {
                // Map the ViewModel to the Data Model
                var tour = new Tour
                {
                    Name = tourVM.Name,
                    Description = tourVM.Description,
                    Price = tourVM.Price,
                    Image = tourVM.Image,
                    Minor = tourVM.Minor,
                    Address = new Address()
                    {
                        Street = tourVM.Address.Street,
                        City = tourVM.Address.City,
                        Country = tourVM.Address.Country
                    },
                };

                // Add the tour to the repository
                _tourRepository.Add(tour);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Unsuccessful");
            }

            // If model state is invalid, return to the creation form with provided data
            return View(tourVM);
        }

        // Action method to display the tour edit form; only accessible by admins
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var tour = await _tourRepository.GetByIdAsync(id);
            if (tour == null) return View("Error");

            var tourVM = new EditTourViewModel
            {
                Name = tour.Name,
                Description = tour.Description,
                Price = tour.Price,
                Image = tour.Image,
                AddressId = tour.AddressId,
                Address = tour.Address,
                Minor = tour.Minor,
            };

            return View(tourVM);
        }

        // Action method to handle the submission of the tour edit form
        [HttpPost]
        public IActionResult Edit(int id, EditTourViewModel tourVM)
        {
            // Validate the model data
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit the excursion");
                return View("Edit", tourVM);
            }

            // Map the ViewModel to the Data Model
            var tour = new Tour
            {
                Id = id,
                Name = tourVM.Name,
                Description = tourVM.Description,
                Price = tourVM.Price,
                Image = tourVM.Image,
                Minor = tourVM.Minor,
                Address = new Address()
                {
                    Street = tourVM.Address.Street,
                    City = tourVM.Address.City,
                    Country = tourVM.Address.Country
                },
            };

            // Update the tour in the repository
            _tourRepository.Update(tour);
            return RedirectToAction("Index");
        }
    }
}

Views/Booking/Book.cshtml
@using Excursion.ViewModels
@model BookViewModel

@{
    ViewData["Title"] = "Book";
}

<div class="form">

    <h2>Book</h2>
    <br>
    <form asp-action="Book">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="@Model.Tour.Name" class="@Model.Tour.Name">Excursion Name</label>
            <input asp-for="@Model.Tour.Name" class="form-control" disabled />
            <span asp-validation-for="@Model.Tour.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TourDate" class="Date">Date</label>
            <input id="TourDate" asp-for="TourDate" class="form-control" type="date" />
            <span asp-validation-for="@Model.Tour.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="NumberOfGuests" class="NumberOfGuests">Number Of Guests</label>
            <input asp-for="NumberOfGuests" class="form-control" value="1" min="1" max="8" />
            <input id="Tour_Price" asp-for="@Model.Tour.Price" class="form-control" hidden />
            <span asp-validation-for="@Model.Tour.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="BookingNotes" class="BookingNotes">Notes:</label>
            <input asp-for="BookingNotes" class="form-control" required />
            <span asp-validation-for="@Model.Tour.Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TotalCost" class="TotalCost">Total Cost</label>
            <input asp-for="TotalCost" class="form-control" disabled />
            <span asp-validation-for="TotalCost" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input class="button" asp-controller="Booking" asp-action="Book" asp-route-id="@Model.Tour.Id" type="submit"
                value="Book Now" />
            <a class="button" asp-controller="Tour" asp-action="Index">Cancel</a>
        </div>
    </form>

</div>

@section Scripts {
    <script>
        window.onload = function () {
            var date = new Date();
            date.setDate(date.getDate() + 1);  // Set the date to tomorrow

            // Format the date in YYYY-MM-DD format
            var dateString = date.toISOString().split('T')[0];
            document.getElementById('TourDate').defaultValue = dateString;
            document.getElementById('TourDate').setAttribute('min', dateString);
        };

        // Get pricePerGuest from the hidden input field.
        var pricePerGuest = Number(document.getElementById('Tour_Price').value);

        // Event listener for when number of guests changes.
        document.getElementById('NumberOfGuests').addEventListener('input', updateTotalCost);

        // Function to update total cost.
        function updateTotalCost() {
            var numberOfGuests = Number(document.getElementById('NumberOfGuests').value);
            var totalCost = pricePerGuest * numberOfGuests;
            document.getElementById('TotalCost').value = '£' + totalCost.toFixed(2);
        }

        // Call updateTotalCost function when page loads.
        document.addEventListener('DOMContentLoaded', updateTotalCost);

    </script>
}

Views/Booking/Confirmation.cshtml
@using Excursion.Models
@model Booking

<div class="form">
    <h1>Thank you for your booking!</h1>
    <p>Your booking has been confirmed. Here are the details:</p>
    <p>Tour: @Model.Tour.Name</p>
    <p>Date: @Model.TourDate.ToShortDateString()</p>
    <p>Number of Guests: @Model.NumberOfGuests</p>
    <p>Total Cost: £@Model.TotalCost</p>
    <p>We look forward to seeing you on the tour!</p>
    <a class="btn btn-primary" asp-controller="Dashboard" asp-action="Index">Go to My Bookings</a>
</div>


<style>

    main {
        padding: 20px 0;
        text-align: left;
        font-family: Arial, sans-serif;
    }

    main h1 {
        color: #005676;
        margin-bottom: 20px;
        font-size: 2em;
    }
    
    main p {
        color: #343a40;
        margin-bottom: 15px;
        font-size: 1.2em;
        line-height: 1.5;
    }

    .btn-primary {
        color: #fff;
        background-color: #005676;
        border: none;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
        font-size: 1.1em;
        margin-top: 20px;
        display: inline-block;
      
    }
</style>